public class AuraResponse {
    /**

    @AuraEnabled @testVisible
    public Boolean isSuccess{get; set;}
    @AuraEnabled @testVisible
    public String message{get; set;}
    @AuraEnabled @testVisible
    public String response{get; set;}
    
    public AuraResponse(Boolean isSuccess, String message, String response) {
        this.isSuccess = isSuccess;
        this.message   = message;
        this.response  = response;
    }
*/
}